#!/usr/bin/expect
spawn fdisk /dev/sdb
expect "*Command*"
send "d\r"
expect "*Partition number*"
send "2\r"
expect "*Command*"
send "n\r"
expect "*Partition type*"
send "p\r"
expect "*Partition number*"
send "\r"
expect "*First sector*"
send "\r"
expect "*Last sector*"
send "\r"
expect "*remove the signature?*"
send "n\r"
expect "*Command*"
send "w\r"
expect {
    timeout {puts "took too much time"}
    eof     {puts "finished in time"}
}
spawn resize2fs /dev/sdb2
expect eof {puts "done resize"}
